language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
- nosetests tests/ --with-coverage
- flake8 demo_data_generators
- nosetests analysis_tools/ --with-coverage
- flake8 analysis_tools
# Run analysis on code base
after_script:
- pylint demo_data_generators
- pyline analysis_tools
